repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    - id: check-docstring-first
    - id: check-toml
    - id: check-yaml
    - id: trailing-whitespace

-   repo: https://github.com/ambv/black
    rev: 21.5b1
    hooks:
    - id: black
      language_version: python3.9

-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
    - id: flake8
      additional_dependencies:
          - 'flake8-builtins'
          - 'flake8-docstrings'
          - 'flake8-import-order'
          - 'pycodestyle'
          - 'pydocstyle'

-   repo: https://github.com/terrencepreilly/darglint
    rev: v1.8.0
    hooks:
    - id: darglint
